### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte

### ISSUE THREAD

**Issue by ardianumam** [google-research/uda#117]
Hi,

Thanks for the awesome work! 
As written in the title, I got decoding error when running `bash scripts/preprocess.sh --aug_copy=${AUG_COPY}` for CIFAR10. Below is the completed error message. Any direction? Thanks!
```
Traceback (most recent call last):
  File "preprocess.py", line 377, in <module>
    tf.app.run(main)
  File "/home/user/anaconda3/envs/tf113/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "preprocess.py", line 322, in main
    data = load_dataset()
  File "preprocess.py", line 183, in load_dataset
    labels = np.load(inf, encoding='bytes')
  File "/home/user/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 423, in load
    magic = fid.read(N)
  File "/home/user/anaconda3/envs/tf113/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 132, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length, status))
  File "/home/user/anaconda3/envs/tf113/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 100, in _prepare_value
    return compat.as_str_any(val)
  File "/home/user/anaconda3/envs/tf113/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 107, in as_str_any
    return as_str(value)
  File "/home/user/anaconda3/envs/tf113/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 80, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
```

**Comment by ardianumam** [comment]
UPDATE: 
The problem was because I used Python 3.x, and would not be encountered when using Python 2.7.
