### ISSUE TITLE
can't concat str to bytes

### ISSUE THREAD

**Issue by miluki01** [google-research/uda#22]
When I ran to this:
bash scripts/prepro.sh --max_seq_length=${MAX_SEQ_LENGTH}
It gives me the error:
(tf) lab01@ai-lab01:/data/projects/uda/text$ bash scripts/prepro.sh --max_seq_length=${MAX_SEQ_LENGTH}
Traceback (most recent call last):
  File "preprocess.py", line 573, in <module>
    app.run(main)
  File "/data/miniconda3/envs/tf/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/data/miniconda3/envs/tf/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "preprocess.py", line 540, in main
    vocab_file=FLAGS.vocab_file, do_lower_case=FLAGS.do_lower_case)
  File "/data/projects/uda/text/utils/tokenization.py", line 69, in __init__
    self.vocab = load_vocab(vocab_file)
  File "/data/projects/uda/text/utils/tokenization.py", line 39, in load_vocab
    token = reader.readline()
  File "/data/miniconda3/envs/tf/lib/python3.7/codecs.py", line 558, in readline
    data = self.read(readsize, firstline=True)
  File "/data/miniconda3/envs/tf/lib/python3.7/codecs.py", line 500, in read
    data = self.bytebuffer + newdata
TypeError: can't concat str to bytes
Traceback (most recent call last):
  File "preprocess.py", line 573, in <module>
    app.run(main)
  File "/data/miniconda3/envs/tf/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/data/miniconda3/envs/tf/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "preprocess.py", line 540, in main
    vocab_file=FLAGS.vocab_file, do_lower_case=FLAGS.do_lower_case)
  File "/data/projects/uda/text/utils/tokenization.py", line 69, in __init__
    self.vocab = load_vocab(vocab_file)
  File "/data/projects/uda/text/utils/tokenization.py", line 39, in load_vocab
    token = reader.readline()
  File "/data/miniconda3/envs/tf/lib/python3.7/codecs.py", line 558, in readline
    data = self.read(readsize, firstline=True)
  File "/data/miniconda3/envs/tf/lib/python3.7/codecs.py", line 500, in read
    data = self.bytebuffer + newdata
TypeError: can't concat str to bytes
Traceback (most recent call last):
  File "preprocess.py", line 573, in <module>
    app.run(main)
  File "/data/miniconda3/envs/tf/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/data/miniconda3/envs/tf/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "preprocess.py", line 540, in main
    vocab_file=FLAGS.vocab_file, do_lower_case=FLAGS.do_lower_case)
  File "/data/projects/uda/text/utils/tokenization.py", line 69, in __init__
    self.vocab = load_vocab(vocab_file)
  File "/data/projects/uda/text/utils/tokenization.py", line 39, in load_vocab
    token = reader.readline()
  File "/data/miniconda3/envs/tf/lib/python3.7/codecs.py", line 558, in readline
    data = self.read(readsize, firstline=True)
  File "/data/miniconda3/envs/tf/lib/python3.7/codecs.py", line 500, in read
    data = self.bytebuffer + newdata
TypeError: can't concat str to bytes

**Comment by qizhex** [comment]
Hi, the code was tested under python2 instead of python3. The function that threw the error was adapted from BERT's initially released code. It seems they have [fixed it](https://github.com/google-research/bert/blob/master/tokenization.py#L121) for python3.
