### ISSUE TITLE
TypeError: can't concat str to bytes

### ISSUE THREAD

**Issue by azamatolegen** [google-research/uda#66]
Thanks for such a great work. After reading the paper I wanted to reproduce experiments, but I am very new to this field. When running the third line of code which is:

 # Preprocessing
bash scripts/prepro.sh --max_seq_length=${MAX_SEQ_LENGTH}

 I am receiving following error:

Traceback (most recent call last):
  File "preprocess.py", line 573, in <module>
    app.run(main)
  File "/home/user/.local/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/user/.local/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "preprocess.py", line 540, in main
    vocab_file=FLAGS.vocab_file, do_lower_case=FLAGS.do_lower_case)
  File "/home/user/Desktop/uda-master/text/utils/tokenization.py", line 69, in __init__
    self.vocab = load_vocab(vocab_file)
  File "/home/user/Desktop/uda-master/text/utils/tokenization.py", line 39, in load_vocab
    token = reader.readline()
  File "/home/user/anaconda3/envs/transformers/lib/python3.7/codecs.py", line 558, in readline
    data = self.read(readsize, firstline=True)
  File "/home/user/anaconda3/envs/transformers/lib/python3.7/codecs.py", line 500, in read
    data = self.bytebuffer + newdata
TypeError: can't concat str to bytes

How can i fix that? Any help is highly appreciated!

**Comment by qizhex** [comment]
Are you using python2 or python3? Sorry the code was tested in python2.
