### ISSUE TITLE
tensorflow-probability version for back translation

### ISSUE THREAD

**Issue by yusagi0603** [google-research/uda#75]
I have set up the environment that can run the training part perfectly, but when I wanted to try back translation on my data, it gave error like this:
*** forward translation ***
Traceback (most recent call last):
  File "/home/yuu/vir_env/tf-uda/bin/t2t-decoder", line 7, in <module>
    from tensor2tensor.bin import t2t_decoder
  File "/home/yuu/vir_env/tf-uda/local/lib/python2.7/site-packages/tensor2tensor/bin/t2t_decoder.py", line 36, in <module>
    from tensor2tensor.bin import t2t_trainer
  File "/home/yuu/vir_env/tf-uda/local/lib/python2.7/site-packages/tensor2tensor/bin/t2t_trainer.py", line 24, in <module>
    from tensor2tensor import models  # pylint: disable=unused-import
  File "/home/yuu/vir_env/tf-uda/local/lib/python2.7/site-packages/tensor2tensor/models/__init__.py", line 25, in <module>
    from tensor2tensor.layers import modalities  # pylint: disable=g-import-not-at-top
  File "/home/yuu/vir_env/tf-uda/local/lib/python2.7/site-packages/tensor2tensor/layers/modalities.py", line 28, in <module>
    from tensor2tensor.layers import common_attention
  File "/home/yuu/vir_env/tf-uda/local/lib/python2.7/site-packages/tensor2tensor/layers/common_attention.py", line 31, in <module>
    from tensor2tensor.layers import area_attention
  File "/home/yuu/vir_env/tf-uda/local/lib/python2.7/site-packages/tensor2tensor/layers/area_attention.py", line 23, in <module>
    from tensor2tensor.layers import common_layers
  File "/home/yuu/vir_env/tf-uda/local/lib/python2.7/site-packages/tensor2tensor/layers/common_layers.py", line 30, in <module>
    import tensorflow_probability as tfp
  File "/home/yuu/vir_env/tf-uda/local/lib/python2.7/site-packages/tensorflow_probability/__init__.py", line 68, in <module>
    _ensure_tf_install()
  File "/home/yuu/vir_env/tf-uda/local/lib/python2.7/site-packages/tensorflow_probability/__init__.py", line 65, in _ensure_tf_install
    present=tf.__version__))
ImportError: This version of TensorFlow Probability requires TensorFlow version >= 1.15; Detected an installation of version 1.13.1. Please upgrade TensorFlow to proceed.
*** backward translation ***

But if I upgrade to tf 1.15, it gave another error like this:

Traceback (most recent call last):
  File "/home/yuu/vir_env/tf-uda/bin/t2t-decoder", line 7, in <module>
    from tensor2tensor.bin import t2t_decoder
  File "/home/yuu/vir_env/tf-uda/local/lib/python2.7/site-packages/tensor2tensor/bin/t2t_decoder.py", line 36, in <module>
    from tensor2tensor.bin import t2t_trainer
  File "/home/yuu/vir_env/tf-uda/local/lib/python2.7/site-packages/tensor2tensor/bin/t2t_trainer.py", line 24, in <module>
    from tensor2tensor import models  # pylint: disable=unused-import
  File "/home/yuu/vir_env/tf-uda/local/lib/python2.7/site-packages/tensor2tensor/models/__init__.py", line 79, in <module>
    from tensor2tensor.models.video import savp
  File "/home/yuu/vir_env/tf-uda/local/lib/python2.7/site-packages/tensor2tensor/models/video/savp.py", line 36, in <module>
    gan_losses = tf.contrib.gan.losses.wargs
  File "/home/yuu/vir_env/tf-uda/local/lib/python2.7/site-packages/tensorflow_core/python/util/lazy_loader.py", line 63, in __getattr__
    return getattr(module, item)
AttributeError: 'module' object has no attribute 'gan'

Can anyone helps? Thanks.

**Comment by nikeshnaik** [comment]
try pip install tensor2tensor==1.8.0

**Comment by yusagi0603** [comment]
Thanks for the suggestion!
I will give it a try recently.

2020年3月3日火曜日 Nikesh Naik <notifications@github.com>:

**Comment by ahnjaewoo** [comment]
I recently solved this problem with the following options. Try it!
```
tensorflow-gpu==1.13.2
tensor2tensor==1.13.4
tensorflow-probability==0.6.0
mesh-tensorflow==0.0.5
```
